spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/point_payment_lab?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:lab}
    password: ${DB_PASSWORD:lab}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: ${SERVER_PORT:8080}

voucher-provider:
  mock-base-url: ${VOUCHER_PROVIDER_BASE_URL:http://localhost:${SERVER_PORT:8080}/mock/voucher-provider}

payment:
  redis-idempotency:
    enabled: ${PAYMENT_REDIS_IDEMPOTENCY_ENABLED:true}
    address: ${REDIS_ADDRESS:redis://127.0.0.1:6379}
    client-id: ${PAYMENT_IDEMPOTENCY_CLIENT_ID:point-payment-lab-mall}
    result-ttl: ${PAYMENT_IDEMPOTENCY_RESULT_TTL:1h}
    lock-wait-time: ${PAYMENT_IDEMPOTENCY_LOCK_WAIT_TIME:500ms}
